<section>
    <div class="row aBout_us-banner-section reveal pt-md-2">
        <h1>About Us</h1>
        <div class="col-md-6 text-center text-md-start ps-md-0 ">
            <img src="images/aboutus_banner-home2.jpg" alt="">
        </div>
        <div class="col-md-6 m-auto">

            <p>Leelija Web Solutions, an ISO 9001:2015 certified online Marketplace. We are enhancing our
                business with the same tactics that we employ to our clients. Our aim is quite clear like
                crystal to help people grow their businesses through an effective and efficient way.</p>
            <p class="mt-4">
                Our main
                focus areas are numbers of online Applications, Business Development Software, Blogs, Guest Post
                Services, On-Page SEO, Blogs + Domain name + Content with good metrics, live ready website that
                includes a detailed description covering all aspects of your business and you as entrepreneurs,
                etc. In an industry where changes are being quite frequent, it’s our duty to stay always far
                from changes.
            </p>
            <div class="aBOUT_btn_div">
                <a href="about.php">
                    <button value="Send" class="my-buttons-hover text-center mt-4 bn21">Know More</button>
                </a>
            </div>
        </div>
    </div>
</section>