<section class="market_place_main  text-center mt-4">
    <h1 class=" fs-1 fw-bolder my-2"><span class="aegean-blue-color fw-bold"></span>Explore</span> The
        <span class="aegean-blue-color fw-bold">Marketplace</span>
    </h1>
    <div class="">
        You Are Not Small,<span class="aegean-blue-color"> Join</span> and <span class="aegean-blue-color">Build</span>
        Your <span class="aegean-blue-color">Business</span>
    </div>
    <div class="row mt-4">
        <div class="col-md-6">
            <div class="cube "></div>
            <div class="cube "></div>
            <img src="images/banner-new.png" class="w-75" alt="">
        </div>
        <div class="col-md-6 text-start m-auto">
            <p>Discover a world of unique treasures and unbeatable deals at our one-stop marketplace. Explore a wide
                range of products and find something special just for you. Unbeatable deals and friendly customer
                service. Join us today for an unforgettable shopping experience.</p>
            <div class="d-flex justify-content-center">
          <a href="domains.php">
                    <button value="Send" class="my-buttons-hover text-center mt-4 bn21">Explore Now</button>
                     </a>
            </div>
        </div>

    </div>
    <!-- <a href="services.php" class="text-uppercase btn-explore-banner btn blue_btn">explore now</a> -->

</section>