<section class="new_section text-center mt-5">
    <h1 class=" aegean-blue-color fs-1 fw-bolder mt-4 mb-2">Latest Blogs</h1>
    <div class="row mt-4 justify-content-evenly">
        <div class="text-center card-width">
            <div class="card card1">
                <a href="#">
                    <div class="card-img">
                        <img class="img-fluid" src="images/banner-new.jpg" alt="">
                        <div class="custom-badge">Technology</div>
                    </div>
                    <div class="box_container">
                        <div class="tag">
                            <span><i class="fa-regular fa-clock tag_icon"></i> 26 March 2022 </span>
                            <span><i class="fa-solid fa-user-tie tag_icon"></i> Windstrip</span>
                        </div>
                        <h4 class="card_title">What is holding back the..</h3>
                            <div class="learn_more">
                                <a href="#"><i class="fa-solid fa-arrow-right pre_icon"></i> Learn more <i
                                        class="fa-solid fa-arrow-right post_icon"></i></a>
                                </h5>
                            </div>
                    </div>
                </a>
            </div>
        </div>

        <div class="text-center card-width">
            <div class="card card1">
                <a href="#">
                    <div class="card-img">
                        <img class="img-fluid" src="images/banner-new.jpg" alt="">
                        <div class="custom-badge">Technology</div>
                    </div>
                    <div class="box_container">
                        <div class="tag">
                            <span><i class="fa-regular fa-clock tag_icon"></i> 26 March 2022 </span>
                            <span><i class="fa-solid fa-user-tie tag_icon"></i> Windstrip</span>
                        </div>
                        <h4 class="card_title">What is holding back the..</h4>
                        <div class="learn_more">
                            <a href="#"><i class="fa-solid fa-arrow-right pre_icon"></i> Learn more <i
                                    class="fa-solid fa-arrow-right post_icon"></i></a>
                            </h5>
                        </div>
                    </div>
                </a>
            </div>
        </div>

        <div class="text-center card-width">
            <div class="card card1">
                <a href="#">
                    <div class="card-img">
                        <img class="img-fluid" src="images/banner-new.jpg" alt="">
                        <div class="custom-badge">Technology</div>
                    </div>
                    <div class="box_container">
                        <div class="tag">
                            <span><i class="fa-regular fa-clock tag_icon"></i> 26 March 2022 </span>
                            <span><i class="fa-solid fa-user-tie tag_icon"></i> Windstrip</span>
                        </div>
                        <h4 class="card_title">What is holding back the..</h4>
                        <div class="learn_more">
                            <a href="#"><i class="fa-solid fa-arrow-right pre_icon"></i> Learn more <i
                                    class="fa-solid fa-arrow-right post_icon"></i></a>
                            </h5>
                        </div>
                    </div>
                </a>
            </div>
        </div>

        <div class="text-center card-width">
            <div class="card card1">
                <a href="#">
                    <div class="card-img">
                        <img class="img-fluid blog_thumb" src="images/banner-new.jpg" alt="">
                        <div class="custom-badge">Technology</div>
                    </div>
                    <div class="box_container">
                        <div class="tag">
                            <span><i class="fa-regular fa-clock tag_icon"></i> 26 March 2022 </span>
                            <span><i class="fa-solid fa-user-tie tag_icon"></i> Windstrip</span>
                        </div>
                        <h4 class="card_title">What is holding back the..</h4>
                        <div class="learn_more">
                            <a href="#"><i class="fa-solid fa-arrow-right pre_icon"></i> Learn more <i
                                    class="fa-solid fa-arrow-right post_icon"></i></a>
                            </h5>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <button class="btn mt-5 explore_btn text-center">More Articles</button>

</section>