<section class="wthfour_section px-md-5  m-0">

    <div class="row  justify-content-center m-auto ">
        <div class="col-lg-3 col-md-12  col-sm-12 xm-12 justify-content-center m-auto card-width3 ">
            <div class="card cd_background">
                <div class="card-body cd_body">
                    <h4 class="card-title text-center fw-bold ">Our Services</h4>
                    <p class="card-text text-center text-light fs-6 p-3 mt-4">We are providing you the best
                        quality online and Business Development services.Our Expert Team always helps you
                        bring
                        your goal closer to you.
                    </p>
                    <div class="d-flex justify-content-center">
                        <a href="services.php" class="btn  rounded-pill bbtnn ">Explore Services</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-9 col-sm-9 row cd-rows d-flex justify-content-center">
            <div class="col-lg-4  p-3  card-width2">
                <div class="card plaincard " style="background: #cfe8ff;">
                    <div class="card-body">
                        <img src="./images/icons/web-development.png " class="w-25" alt="">
                        <h5 class="card-title pt-3 fw-semibold">Web Development</h5>
                        <div class="divi-ne pt-3">
                            <span class="atag_style text-capitalize">Secure</span>
                            <span class="atag_style text-capitalize">Seo Friendly</span>
                            <!-- <a class="atag_style " href="">Design</a> -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4  p-3  card-width2">
                <div class="card plaincard " style="background: antiquewhite;">
                    <div class="card-body">
                        <img src="./images/icons/blog.png " class="w-25" alt="">
                        <h5 class="card-title pt-3 fw-semibold">SEO</h5>
                        <div class="divi-ne pt-3">
                            <span class="atag_style text-capitalize" href="">On Top Results</span>
                            <span class="atag_style text-capitalize" href="">Better Reach</span>
                            <!-- <a class="atag_style " href="">Design</a> -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4  p-3  card-width2">
                <div class="card plaincard " style="background: darkgray;">
                    <div class="card-body ">
                        <img src="./images/icons/business-solution.png " class="w-25" alt="">
                        <h5 class="card-title pt-3 fw-semibold">Guest Posting</h5>
                        <div class="divi-ne pt-3">
                            <span class="atag_style text-capitalize" href="">cheapish</span>
                            <span class="atag_style text-capitalize" href="">on time</span>
                            <!-- <a class="atag_style " href="">Design</a> -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4  p-3  card-width2">
                <div class="card plaincard " style="background: #ebddd9;">
                    <div class="card-body">
                        <img src="images/icons/creativity.png" class="w-25" alt="">
                        <h5 class="card-title pt-3 fw-semibold">Content Marketing</h5>
                        <div class="divi-ne pt-3">
                            <span class="atag_style text-capitalize" href="">remarkable</span>
                            <span class="atag_style text-capitalize" href="">seo friendly</span>
                            <!-- <a class="atag_style " href="">Design</a> -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 p-3  card-width2">
                <div class="card plaincard " style="background: #ebe3eb;">
                    <div class="card-body">
                        <img src="./images/icons/online-reputation.png" class="w-25" alt="">
                        <h5 class="card-title pt-3 fw-semibold">Branding Services</h5>
                        <div class="divi-ne pt-3">
                            <span class="atag_style text-capitalize">marketing</span>
                            <span class="atag_style text-capitalize">value addition</span>
                            <!-- <a class="atag_style " href="">Design</a> -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4  p-3  card-width2">
                <div class="card plaincard " style="background: #f3caca;">
                    <div class="card-body">
                        <img src="./images/icons/digital-marketing.png" class="w-25" alt="">
                        <h5 class="card-title pt-3 fw-semibold">Social Media Marketing</h5>
                        <div class="divi-ne pt-3">
                            <span class="atag_style text-capitalize">better reach</span>
                            <span class="atag_style text-capitalize">more client</span>
                            <!-- <a class="atag_style " href="">Design</a> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>