<section class="clientsides-item reveal" id="clientslogo">
    <div class="containering ">
        <div>
            <h2 class="px-3 px-md-0">Our clients earned brand mentions from <strong>publications
                    like...</strong></h2>
        </div>

        <div class="row clientside-logo-row">
            <div class="clientsides-logo-wrap col-sm-6 col-md-3">
                <img src="images/clients-logos/cc1.png" class="cslogo-img-responsiving w-100" alt="">
            </div>
            <div class="clientsides-logo-wrap  col-sm-6 col-md-3">
                <img src="images/clients-logos/khatabook3.png" class="cslogo-img-responsiving" alt="">
            </div>
            <div class="clientsides-logo-wrap  col-sm-6 col-md-3">
                <img src="images/clients-logos/specscart3.png " class="cslogo-img-responsiving" alt="">
            </div>
            <div class="clientsides-logo-wrap col-sm-6 col-md-3 ">
                <img src="images/clients-logos/namecheap1.png" class="cslogo-img-responsiving " alt="">
            </div>
            <div class="clientsides-logo-wrap col-sm-6 col-md-3">
                <img src="images/clients-logos/cs1.png" class="cslogo-img-responsiving" alt="">
            </div>
            <div class="clientsides-logo-wrap  col-sm-6 col-md-3">
                <img src="images/clients-logos/icademy1.png" class="cslogo-img-responsiving" alt="">
            </div>
            <div class="clientsides-logo-wrap  col-sm-6 col-md-3">
                <img src="images/clients-logos/ISB3.png" class="cslogo-img-responsiving" alt="">
            </div>
            <div class="clientsides-logo-wrap  col-sm-6 col-md-3 ">
                <img src="images/clients-logos/recovery3.png" class="cslogo-img-responsiving" alt="">
            </div>

        </div>
    </div>
</section>