<!--================================= Client Review section Start =================================-->

<section class="sliderbar text-center mt-5 reveal">
<h2 class="what-others-say-testimonial  mt-0 mb-0">TESTIMONIAL</h2>
        <h1 class="what-others-say-bo-slider-h1   my-3 my-md-2">What <span>Our Client</span> Says</h1>
        <div class="container" style="max-width: 1100px; padding: 0;">
            <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators ">
                    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
                        aria-current="true" aria-label="Slide 1"></button>
                    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                        aria-label="Slide 2"></button>
                    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                        aria-label="Slide 3"></button>
                    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3"
                        aria-label="Slide 4"></button>
                </div>

                <!-- ======================= Carousel inner Start ======================= -->
                <div class="carousel-inner">

                    <!-- =============== Review One =============== -->
                    <div class="carousel-item active slider">
                        <h4 class="what-others-say-bo-ci-h4">"Honestly, they are the best in the digital marketing world. Very much committed and punctual towards their delivery. Definitely, we will use the services of  Leelija in the upcoming years."</h4>
                        <div class="containerslider">
                            <img src="images/icons/male-user.webp" class="imageslider" alt="...">
                            <div class="sliderbox1">

                                <h5 class="paraname">Kishu Setia</h5>
                                <p class="para1">Experienced Blogger</p>
                            </div>
                        </div>
                        <div class="carousel-caption d-none d-md-block">

                        </div>
                    </div>
                    <!-- =============== Review One End =============== -->



                    <!-- =============== Review Two =============== -->
                    <div class="carousel-item slider">
                        <h4 class="what-others-say-bo-ci-h4">"Leelija did a fantastic job with our online marketing strategy.We have to say they have a great reporting process and are always touched with our manager and  outreach team."</h4>
                        <div class="containerslider">
                            <img src="images/icons/female-user.webp" class="imageslider" alt="...">
                            <div class="sliderbox1">

                                <h5 class="paraname">Gemma Bell</h5>
                                <p class="para1">Marketing Expert</p>
                            </div>
                        </div>
                        <div class="carousel-caption d-none d-md-block">

                        </div>
                    </div>

                    <!-- =============== Review Two End =============== -->



                    <!-- =============== Review Three =============== -->
                    <div class="carousel-item slider">
                        <h4 class="what-others-say-bo-ci-h4">"I really appreciate the business relationship we have had with Leelija Team for the last 1 year. They have helped us in website development and design for our organic growth."</h4>
                        <div class="containerslider">
                            <img src="images/icons/female-user.webp" class="imageslider" alt="...">
                            <div class="sliderbox1">

                                <h5 class="paraname">Stewart</h5>
                                <p class="para1">Indivisual Blogger</p>
                            </div>
                        </div>
                        <div class="carousel-caption d-none d-md-block">

                        </div>
                    </div>
                    <!-- =============== Review Three End =============== -->


                    <!-- =============== Review Four =============== -->
                    <div class="carousel-item slider">
                        <h4 class="what-others-say-bo-ci-h4">"From a digital marketing point of view, I am highly impressed with the hard work of the Leelija Team. They are amazing and so has been their support and  contribution."</h4>
                        <div class="containerslider">
                            <img src="images/icons/male-user.webp" class="imageslider" alt="...">
                            <div class="sliderbox1">

                                <h5 class="paraname">Louie Arim</h5>
                                <p class="para1">Marketing Team Lead</p>
                            </div>
                        </div>
                        <div class="carousel-caption d-none d-md-block">

                        </div>
                    </div>
                    <!-- =============== Review Four End =============== -->

                </div>
                <!-- ======================= Carousel inner End ======================= -->

                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
                    data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"><i
                            class="fa-solid fa-arrow-left-long iconbutton"></i></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
                    data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"><i
                            class="fa-solid fa-arrow-right-long iconbutton"></i></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>  
    </section>

    <!------------------------------------ Client Review section End ------------------------------------->