<section class="secxn">
    <div class="row w-100 m-0" style="overflow: hidden;">
        <div class="  col-lg-9 col-md-12 col-sm-12 colm1">
            <h5 class="aegean-blue-color mb-3 "> &#8213; WORKS ABOUT</h5>
            <h3 class=" mb-0" style="font-weight: 700;">Trusted by 5000+</h3>
            <h3 class=" mb-3" style="font-weight: 700;">Happy Customers</h3>
            <p class=" mb-4">We’re a team of SEO and development experts who provide a complete set of
                integrated services to scale your company’s digital growth.</p>
            <h6 class="mb-3 tickline"><i class="fa-solid fa-circle-check pe-2 tickicn"></i> 100% Client
                Satisfaction
            </h6>
            <h6 class=" mb-5 tickline"> <i class="fa-solid fa-circle-check pe-2 tickicn"></i> World Class
                Worker
            </h6>
            <div class="d-flex justify-content-center justify-content-lg-start">
                <a href="<?= URL?>contact.php" class="btn btn-primary bbtnn ">Let's Connect</a>
            </div>
        </div>
        <div class="divvcs col-lg-3 col-md-12 col-sm-12 ">
            <img src="images/pplgroup.jpg" class="imggy" width="500px" height="350px" alt="">
            <div class="textinpicture">
            </div>
        </div>
    </div>
</section>